from .schemas import Company


# The first backend slice deliberately uses the same fixtures as frontend/src/data.ts.
COMPANIES: list[Company] = [
    Company(
        id="toan-cau",
        code="HS-2023-8901",
        name="Công ty TNHH Giải pháp Công nghệ Toàn cầu",
        shortName="Công nghệ Toàn cầu",
        owner="Marcus Chen",
        amount="$450,000",
        purpose="Vốn lưu động",
        sla="2h 15m",
        submitted="10:45 24/10",
        agent="AI-Agent-Alpha",
        score=82,
        status="Đang chờ rà soát",
        risk="Trung bình",
        issue="Chênh lệch thu nhập > 15%",
        recommendation="CREATE_TAX_RECONCILIATION_TASK",
        consensus=["Đã xác minh thực thể", "Địa chỉ khớp"],
        objections=["Chênh lệch thu nhập > 15%"],
        agents=[
            {"name": "Agent Tín dụng", "state": "done", "confidence": 92, "result": "CREDIT_THRESHOLD_MET"},
            {"name": "Agent Tuân thủ", "state": "done", "confidence": 98, "result": "AML_VERIFIED"},
            {"name": "Agent Thuế", "state": "running", "confidence": 74, "result": "TAX_RECONCILIATION_REQUIRED"},
            {"name": "Agent Sản phẩm", "state": "optional", "confidence": 85, "result": "ELIGIBLE_FOR_REWARD"},
        ],
    ),
    Company(
        id="hung-phat",
        code="HS-2023-8895",
        name="Công ty TNHH Hưng Phát",
        shortName="Hưng Phát",
        owner="Nguyễn Minh Anh",
        amount="₫8.2 tỷ",
        purpose="Mở rộng nhà xưởng",
        sla="45m",
        submitted="09:12 24/10",
        agent="AI-Agent-Beta",
        score=94,
        status="Chấp nhận",
        risk="Thấp",
        issue="Không có cảnh báo trọng yếu",
        recommendation="APPROVE_WITH_STANDARD_COVENANTS",
        consensus=["Dòng tiền ổn định", "Tài sản bảo đảm hợp lệ", "Không có cảnh báo AML"],
        objections=[],
        agents=[
            {"name": "Agent Tín dụng", "state": "done", "confidence": 96, "result": "CREDIT_THRESHOLD_MET"},
            {"name": "Agent Tuân thủ", "state": "done", "confidence": 99, "result": "AML_VERIFIED"},
            {"name": "Agent Thuế", "state": "done", "confidence": 91, "result": "TAX_MATCHED"},
            {"name": "Agent Sản phẩm", "state": "done", "confidence": 89, "result": "TERM_LOAN_ELIGIBLE"},
        ],
    ),
    Company(
        id="sai-gon",
        code="HS-2023-8872",
        name="Công ty Cổ phần Đầu tư Sài Gòn",
        shortName="Đầu tư Sài Gòn",
        owner="Lê Hoàng Nam",
        amount="₫15 tỷ",
        purpose="Bổ sung vốn dự án",
        sla="1h 30m",
        submitted="16:30 23/10",
        agent="AI-Agent-Alpha",
        score=68,
        status="Từ chối",
        risk="Cao",
        issue="Đòn bẩy tài chính vượt ngưỡng chính sách",
        recommendation="REQUEST_ADDITIONAL_COLLATERAL",
        consensus=["Pháp nhân đã xác minh"],
        objections=["DSCR dưới 1.1x", "Đòn bẩy tài chính 4.8x"],
        agents=[
            {"name": "Agent Tín dụng", "state": "done", "confidence": 88, "result": "CREDIT_THRESHOLD_NOT_MET"},
            {"name": "Agent Tuân thủ", "state": "done", "confidence": 95, "result": "AML_VERIFIED"},
            {"name": "Agent Thuế", "state": "done", "confidence": 82, "result": "TAX_MATCHED"},
            {"name": "Agent Sản phẩm", "state": "required", "confidence": 61, "result": "COLLATERAL_REQUIRED"},
        ],
    ),
    Company(
        id="le-gia",
        code="HS-2023-8850",
        name="Doanh nghiệp tư nhân Lê Gia",
        shortName="DNTN Lê Gia",
        owner="Trần Thanh Hà",
        amount="₫3.6 tỷ",
        purpose="Mua sắm thiết bị",
        sla="3h 05m",
        submitted="14:15 23/10",
        agent="AI-Agent-Gamma",
        score=76,
        status="Đã xác minh",
        risk="Trung bình",
        issue="Thiếu báo cáo công nợ quý gần nhất",
        recommendation="REQUEST_MISSING_DOCUMENTS",
        consensus=["Lịch sử tín dụng tốt", "Thiết bị đủ điều kiện tài trợ"],
        objections=["Thiếu báo cáo công nợ Q3"],
        agents=[
            {"name": "Agent Tín dụng", "state": "done", "confidence": 87, "result": "CREDIT_THRESHOLD_MET"},
            {"name": "Agent Tuân thủ", "state": "done", "confidence": 96, "result": "AML_VERIFIED"},
            {"name": "Agent Thuế", "state": "running", "confidence": 79, "result": "DOCUMENT_PENDING"},
            {"name": "Agent Sản phẩm", "state": "done", "confidence": 84, "result": "EQUIPMENT_LOAN_ELIGIBLE"},
        ],
    ),
]
